#!/usr/bin/env bash
# Enable bash's unofficial strict mode
GITROOT=$(git rev-parse --show-toplevel)
export GITROOT
# shellcheck disable=SC1091
. "${GITROOT}/lib/strict-mode"
strictMode

THIS_SCRIPT=$(basename "${0}")

SRC_DIR="/data/${THIS_SCRIPT}"

cd "${SRC_DIR}" || exit

make
make install DESTDIR=/opt
make install-doc DESTDIR=/opt

function msg_info () {
  local GREEN=$'\033[0;32m'
  local NC=$'\033[0m' # No Color
  printf "%s\n" "${GREEN}${*}${NC}"
}

function msg_error () {
  local LRED=$'\033[01;31m'
  local NC=$'\033[0m' # No Color
  printf "%s\n" "${LRED}${*}${NC}"
}

function cleanup () {
  msg_info "Deleting ${SRC_DIR} directory and compressed file"
  rm -rf "${SRC_DIR}"
}
# Make sure cleanup runs even if this script fails
trap cleanup EXIT

msg_info "Debian dependencies are ${DEB_DEPENDENCIES}"
msg_info "RPM dependencies are ${RPM_DEPENDENCIES}"

DEB_DEPS=""
IFS=','
for i in echo "${DEB_DEPENDENCIES}"; do
  DEB_DEPS="${DEB_DEPS}-d '${i}' "
done
IFS=$'\n\t'

RPM_DEPS=""
IFS=','
for i in echo "${RPM_DEPENDENCIES}"; do
  RPM_DEPS="${RPM_DEPS}-d '${i}' "
done
IFS=$'\n\t'

msg_info "Creating RPM"

RPM_OPTS="fpm -s dir -t rpm -n '${NAME}' -v '${VERSION}' --license '${LICENSE}' -a native --url '${SOURCE}' --iteration '${RELEASE}' ${RPM_DEPS} -m '${MAINTAINER}' --description '${DESCRIPTION}' /opt/usr/=/usr/local"
eval "${RPM_OPTS}"

rpm -qpi "${NAME}-${VERSION}-${RELEASE}.x86_64.rpm"

msg_info "Moving RPM to tmp-files/RPM/"

mv "${NAME}-${VERSION}-${RELEASE}.x86_64.rpm" /data/tmp-files/RPM/

msg_info "Creating DEB"

DEB_OPTS="fpm -s dir -t deb -n '${NAME}' -v '${VERSION}' --license '${LICENSE}' -a native --url '${SOURCE}' --deb-no-default-config-files --iteration '${RELEASE}' ${DEB_DEPS} -m '${MAINTAINER}' --description '${DESCRIPTION}' /opt/usr/=/usr/local"
eval "${DEB_OPTS}"

dpkg-deb -I "${NAME}_${VERSION}-${RELEASE}_amd64.deb"

msg_info "Moving DEB to tmp-files/DEB/"

mv "${NAME}_${VERSION}-${RELEASE}_amd64.deb" /data/tmp-files/DEB/
