#!/usr/bin/env bash
# file is sourced from build-packages.sh
# there is no need to source strict-mode or utils

#==== Start of custom build steps ====
ORIG_PATH="$(pwd)"
cd "${EXTRACTED_FILE}/${NAME}-${VERSION}" || exit

make
make install DESTDIR=/opt
make install-doc DESTDIR=/opt
cd  "${ORIG_PATH}" || exit 1
#===== End of custom build steps =====
